config/routes.rb
Rails.application.routes.draw do
  resources :merchants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attr_name, value)
    unless value =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
      record.errors.add(attr_name, :email, **options.merge(value: value))
    end
  end
end

app/models/concerns/status_validator.rb
class StatusValidator < ActiveModel::EachValidator
  def validate_each(record, attr_name, value)
    unless %w[pending cancelled completed dirbursed].include? value
      record.errors.add(attr_name, :status, **options.merge(value: value))
    end
  end
end

app/models/disbursement.rb
class Disbursement < ActiveRecord::Base
  belongs_to :order
  belongs_to :fee_configuration

  validates :processed_at, presence: true
  validates :value, presence: true
  validates :status, presence: true

  scope :find_by_merchant, (lambda do |merchant_id|
    joins(:merchant).where(id: merchant_id)
  end)

  scope :find_by_day_week, (lambda do |day_week|
    where('from_date < ? AND to_date > ?', day_week, day_week + 6.days)
  end)

end

app/models/fee_configuration.rb
class FeeConfiguration < ActiveRecord::Base
  belongs_to :fee_configurations_type
  has_many :disbursement

  scope :find_by_fee_configurations_type, (lambda do |fee_configurations_type_id|
    where(fee_configurations_type_id: fee_configurations_type_id)
  end)

  scope :find_by_amount, (lambda do |amount|
    where('min_amount > ? AND max_amount < ?', amount)
  end)
end

app/models/fee_configurations_type.rb
class FeeConfigurationsType < ActiveRecord::Base
  has_many :fee_configurations
  has_many :merchants
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  validates :email, presence: true, email: true
  validates :cif, presence: true

  validates_presence_of :name

  has_many :orders
  belongs_to :fee_configurations_type

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :amount, presence: true
  validates :status, presence: true, status: true
  belongs_to :merchant
  belongs_to :shopper
  has_one :disbursement

  scope :find_by_day_week, (lambda do |day_week|
    where('from_date < ? AND to_date > ?', day_week, day_week + 6.days)
  end)
  
end

app/models/shopper.rb
class Shopper < ActiveRecord::Base
  validates :email, presence: true, email: true
  validates :nif, presence: true, nif: true

  has_many :orders

end

app/controllers/api/v1/disbursement_controller.rb
class Api::V1::DisbursementsController < ApplicationController
  # GET /list
  def list
    @disbursements = Api::V1.Orders.Disbursements.call(disbursements_params)

    render json: @disbursements,
           serializer: Api::V1::DisbursementSerializer
  end
end

app/controllers/api/v1/serializer/disbursement.rb
class Api::V1::DisbursementSerializer < ActiveModel::Serializer
  attributes(
    :id,
    :order_id,
    :fee_configuration_id,
    :processed_at,
    :value,
    :status
  )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @merchants = Merchant.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @merchant = Merchant.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def merchant_params
      params.require(:merchant).permit(:name, :email, :cif)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merchant_helper.rb
module MerchantHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsondocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/merchants/_form.html.erb
<%= form_with(model: merchant) do |form| %>
  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
        <% merchant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cif, style: "display: block" %>
    <%= form.text_field :cif %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchant</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>CIF</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.email %></td>
        <td><%= merchant.cif %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New Product</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @merchant.email %>
</p>

<p>
  <strong>CIF:</strong>
  <%= @merchant.cif %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>